name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  # --- PRIMEIRO QUADRADO: CI ---
  build:
    name: Integração Contínua (CI)
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3
      
      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
        
      - name: Rodar teste de validação
        run: |
          python -c "import flask; print('Teste concluido com sucesso!')"

  # --- SEGUNDO QUADRADO: CD ---
  deploy:
    name: Entrega Contínua (CD)
    needs: build  # <- É ISSO AQUI QUE CRIA A LINHA LIGANDO OS DOIS QUADRADOS!
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3
        
      - name: Construir a Imagem Docker
        run: |
          docker build -t meu-projeto-devops:latest .