name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      # --- ETAPA DE CI (Integração Contínua) ---
      - name: Baixar o código do repositório
        uses: actions/checkout@v3
      
      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Instalar dependências
        run: pip install -r requirements.txt
        
      - name: Rodar teste de validação (CI)
        run: python -c "import flask; print('CI: Teste concluído com sucesso!')"

      # --- ETAPA DE CD (Entrega Contínua) ---
      - name: Construir a Imagem Docker (CD)
        run: docker build -t meu-projeto-devops:latest .